# SPDX-FileCopyrightText: 2024 Christina Sørensen
#
# SPDX-License-Identifier: EUPL-1.2

version = 1
SPDX-PackageName = "metamorph"
SPDX-PackageSupplier = "Christina Sørensen <christina@cafkafk.com>"

[[annotations]]
path = "flake.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Christina Sørensen"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "Cargo.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Christina Sørensen"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = ".envrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Christina Sørensen"
SPDX-License-Identifier = "EUPL-1.2"

# pre-commit-hooks.nix noise... sigh
[[annotations]]
path = ".cache/pre-commit/README"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Christina Sørensen"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = ".cache/pre-commit/db.db"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Christina Sørensen"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = ".gitconfig"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Christina Sørensen"
SPDX-License-Identifier = "EUPL-1.2"
